language: cpp
sudo: required

os:
  - osx

osx_image: xcode8.2

branches:
  only:
    - qt-port

cache:
  ccache: true
  directories:
    - $HOME/.cache/macports

before_install: 
  # prep MacPorts
  - stty rows 40 columns 80 # set rows, columns in terminal
  - export PORT_PKG=MacPorts-2.4.1-10.12-Sierra.pkg
  - export PORT_CACHE=$HOME/.cache/macports
  - export PORT_CACHE_PKG=$PORT_CACHE/$PORT_PKG
  - export PORT_CACHE_DROP=$PORT_CACHE/macports.tar.gz
  - mkdir -p $PORT_CACHE
  - ls -l $PORT_CACHE
  - if [[ ! -f $PORT_CACHE_PKG ]]; then wget -O $PORT_CACHE_PKG https://github.com/macports/macports-base/releases/download/v2.4.1/$PORT_PKG ; fi
  - ls -l $PORT_CACHE
  - if [[ -f $PORT_CACHE_DROP ]]; then sudo tar xPf $PORT_CACHE_DROP ; fi
  - if [[ -d /opt/local ]]; then ls -l /opt/local ; fi
  - if [[ ! -f /opt/local/bin/port ]]; then sudo installer -pkg $PORT_CACHE_PKG -target / ; fi
  - export PATH=/opt/local/bin:$PATH
  - sudo port -v selfupdate
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0  gettext ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                  ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxwidgets gettext texinfo       ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/gettext/bin ; fi

install:
  - sudo port -N install qt5-qtbase
  - sudo port -N install wxWidgets-3.0
  - export PATH=/opt/local/libexec/qt5/bin:$PATH

notifications:
  email:
    recipients:
      - kuba@mareimbrium.org
    on_success: change
    on_failure: change

git:
  depth: 10

script: |
  qmake &&
  make

before_cache:
  - 'sudo rm -rf /opt/local/var/macports/build/* /opt/local/var/macports/logs/* || true'
  - sudo tar cf $PORT_CACHE_DROP /opt/local
