language: cpp
sudo: required

os:
  - osx

osx_image: xcode8.2

branches:
  only:
    - qt-port

cache: ccache

before_install: 
  # prep MacPorts
  - stty rows 40 columns 80 # set rows, columns in terminal
  - wget https://github.com/macports/macports-base/releases/download/v2.4.1/MacPorts-2.4.1-10.12-Sierra.pkg
  - sudo installer -pkg MacPorts-2.4.1-10.12-Sierra.pkg -target /
  - export PATH=/opt/local/bin:$PATH
  - sudo port -v selfupdate
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0  gettext ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                  ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxwidgets gettext texinfo       ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/gettext/bin ; fi

install:
  - sudo port -N install qt5-qtbase
  - sudo port -N install wxWidgets-3.0
  - export PATH=/opt/local/libexec/qt5/bin:$PATH

notification:
  email:
    recipients:
      - kuba@mareimbrium.org
    on_success: change
    on_failure: change

git:
  depth: 10

script: |
  qmake &&
  make
